apiVersion: v2
name: webapp
description: Демонстрационное приложение из двух компонентов (frontend + backend) для ДЗ по Helm
type: application
version: 0.1.0      # версия самого чарта
appVersion: "1.0"   # версия приложения по умолчанию