{
 "title": "Homework Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Disk Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Total" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Утилизация CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU %"
    }
   ]
  },
  {
   "title": "Load Average (1/5/15)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "node_load1" },
    { "expr": "node_load5", "legendFormat": "node_load5" },
    { "expr": "node_load15", "legendFormat": "node_load15" }
   ]
  }
 ]
}