apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}-backend
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 80