input {
  tcp {
    port  => 5000
    codec => json_lines
  }
  udp {
    port  => 5000
    codec => json
  }
}

filter {
  # если событие пришло от filebeat и в нём есть вложенный json-лог docker'а — можно распарсить дополнительно
  # (для базового задания не обязательно)
}

output {
  elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
